import React, { useState } from "react";
import { AppState, Persona } from "../types";
import { Users, Cpu, Trash2, Plus, X, Download, UploadCloud, Check, AlertCircle } from "lucide-react";
import { cn } from "../lib/utils";
import { createOllamaModel } from "../lib/llmClient";

export function PersonasTab({ state, setState }: { state: AppState, setState: React.Dispatch<React.SetStateAction<AppState>> }) {
  const [showAddForm, setShowAddForm] = useState(false);
  const [newDisplayName, setNewDisplayName] = useState("");
  const [newModelName, setNewModelName] = useState("");
  const [newSystemPrompt, setNewSystemPrompt] = useState("");
  const [publishingStatus, setPublishingStatus] = useState<Record<string, "idle" | "publishing" | "success" | "error">>({});
  const [publishingError, setPublishingError] = useState<Record<string, string>>({});

  const updatePersona = (id: string, updates: Partial<Persona>) => {
    setState(prev => ({
      ...prev,
      activePersonas: prev.activePersonas.map(p => p.id === id ? { ...p, ...updates } : p)
    }));
  };

  const deletePersona = (id: string) => {
    setState(prev => ({
      ...prev,
      activePersonas: prev.activePersonas.filter(p => p.id !== id)
    }));
  };

  const handleAddPersona = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDisplayName.trim() || !newModelName.trim()) return;

    // Generate unique ID
    const nextNum = state.activePersonas.length > 0 
      ? Math.max(...state.activePersonas.map(p => {
          const match = p.id.match(/\d+/);
          return match ? parseInt(match[0], 10) : 100;
        })) + 1
      : 101;
    const newId = `AI-${nextNum}`;

    const newPersona: Persona = {
      id: newId,
      displayName: newDisplayName.trim(),
      modelName: newModelName.trim(),
      systemPrompt: newSystemPrompt.trim() || `You are ${newDisplayName}. Identify as ${newId}.`
    };

    setState(prev => ({
      ...prev,
      activePersonas: [...prev.activePersonas, newPersona]
    }));

    // Reset form
    setNewDisplayName("");
    setNewModelName("");
    setNewSystemPrompt("");
    setShowAddForm(false);
  };

  const downloadModelfile = (persona: Persona) => {
    const content = `# Modelfile generated by Zachs LLM_CONNECT\nFROM ${persona.modelName}\n\nSYSTEM """\n${persona.systemPrompt}\n"""\n`;
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${persona.displayName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.modelfile`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const publishToOllama = async (persona: Persona) => {
    const targetModelName = persona.displayName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    
    setPublishingStatus(prev => ({ ...prev, [persona.id]: "publishing" }));
    setPublishingError(prev => ({ ...prev, [persona.id]: "" }));

    try {
      await createOllamaModel(state.endpoint, targetModelName, persona.modelName, persona.systemPrompt);
      setPublishingStatus(prev => ({ ...prev, [persona.id]: "success" }));
      
      // Auto-revert success state to idle after 3s
      setTimeout(() => {
        setPublishingStatus(prev => ({ ...prev, [persona.id]: "idle" }));
      }, 3000);
    } catch (err: any) {
      console.error(err);
      setPublishingStatus(prev => ({ ...prev, [persona.id]: "error" }));
      setPublishingError(prev => ({ ...prev, [persona.id]: err.message || "Model creation failed" }));
    }
  };

  if (!state.isConnected) {
    return (
      <div className="flex h-full flex-col items-center justify-center p-6 text-center">
        <Users size={48} className="mb-4 text-zinc-700" />
        <h2 className="mb-2 text-xl font-display font-semibold text-zinc-300">Identity Drift Protection</h2>
        <p className="text-sm text-zinc-500">Connect to a server first to configure mod files and personas.</p>
      </div>
    );
  }

  // Get list of unique model names that were discovered to prefill selection options
  const uniqueDiscoveredModels = Array.from(
    new Set(state.activePersonas.map(p => p.modelName))
  );

  return (
    <div className="flex h-full flex-col gap-6 p-6 overflow-y-auto custom-scrollbar pb-28">
      <div className="flex flex-col gap-2 relative">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-xl font-display font-semibold tracking-tight">
            <Users className="text-cyan-400" />
            Persona Configuration
          </div>
          <button
            onClick={() => setShowAddForm(!showAddForm)}
            className="flex items-center gap-1 px-3 py-1.5 bg-cyan-600 hover:bg-cyan-500 text-xs font-semibold rounded-lg text-white transition-colors"
          >
            {showAddForm ? <X size={14} /> : <Plus size={14} />}
            {showAddForm ? "Cancel" : "Add Persona"}
          </button>
        </div>
        <p className="text-sm text-zinc-400">
          Set up Identity Drift Protection. Ensure each model recognizes its ID # and has the correct Mod File (System Prompt).
        </p>
      </div>

      {/* Add Persona Form */}
      {showAddForm && (
        <div className="rounded-2xl border border-cyan-500/30 bg-zinc-900/60 p-4 shadow-xl backdrop-blur-md animate-fadeIn">
          <h3 className="text-xs font-bold tracking-widest text-cyan-400 uppercase mb-3">Add Custom Persona</h3>
          <form onSubmit={handleAddPersona} className="flex flex-col gap-3">
            <div className="flex gap-3">
              <div className="flex-1 flex flex-col gap-1.5">
                <label className="text-[10px] font-bold text-zinc-500 uppercase">Display Name</label>
                <input
                  type="text"
                  placeholder="e.g. Agent Delta"
                  value={newDisplayName}
                  onChange={(e) => setNewDisplayName(e.target.value)}
                  required
                  className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-xs text-zinc-200 focus:border-cyan-500 focus:outline-none"
                />
              </div>
              <div className="flex-1 flex flex-col gap-1.5">
                <label className="text-[10px] font-bold text-zinc-500 uppercase">Target Model</label>
                <div className="relative">
                  <input
                    type="text"
                    list="discovered-models"
                    placeholder="e.g. llama3:8b"
                    value={newModelName}
                    onChange={(e) => setNewModelName(e.target.value)}
                    required
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-xs text-zinc-200 focus:border-cyan-500 focus:outline-none"
                  />
                  <datalist id="discovered-models">
                    {uniqueDiscoveredModels.map(m => <option key={m} value={m} />)}
                  </datalist>
                </div>
              </div>
            </div>
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold text-zinc-500 uppercase">Mod File / System Prompt</label>
              <textarea
                placeholder="Core behavioral instructions..."
                value={newSystemPrompt}
                onChange={(e) => setNewSystemPrompt(e.target.value)}
                rows={2}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-xs font-mono text-zinc-350 focus:border-purple-500 focus:outline-none resize-none"
              />
            </div>
            <button
              type="submit"
              className="mt-2 w-full py-2 bg-cyan-600 hover:bg-cyan-500 text-xs font-semibold text-white rounded-lg transition-colors"
            >
              Save Persona
            </button>
          </form>
        </div>
      )}

      {/* Personas List */}
      <div className="flex flex-col gap-4">
        {state.activePersonas.map((persona) => (
          <div key={persona.id} className="flex flex-col gap-3 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-4 shadow-xl backdrop-blur-md relative group">
            
            <div className="absolute right-4 top-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              <button
                type="button"
                onClick={() => deletePersona(persona.id)}
                className="p-1.5 rounded bg-red-950/20 text-red-500/70 hover:text-red-500 hover:bg-red-950/40 transition-colors"
                title="Delete Persona"
              >
                <Trash2 size={14} />
              </button>
            </div>

            <div className="flex gap-4">
              <div className="flex-1 flex flex-col gap-1.5">
                <label className="text-[10px] font-bold tracking-widest text-zinc-500 uppercase">Display Name (You see)</label>
                <input
                  type="text"
                  value={persona.displayName}
                  onChange={(e) => updatePersona(persona.id, { displayName: e.target.value })}
                  className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-200 focus:border-cyan-500 focus:outline-none"
                />
              </div>

              <div className="flex-1 flex flex-col gap-1.5">
                <label className="text-[10px] font-bold tracking-widest text-zinc-500 uppercase">Internal ID (They see)</label>
                <input
                  type="text"
                  value={persona.id}
                  disabled
                  className="w-full rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-500 font-mono"
                />
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold tracking-widest text-zinc-500 uppercase flex items-center gap-1"><Cpu size={12}/> Target Model</label>
              <input
                type="text"
                value={persona.modelName}
                disabled
                className="w-full rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-emerald-500/70 font-mono"
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold tracking-widest text-zinc-500 uppercase">Mod File / System Prompt</label>
              <textarea
                value={persona.systemPrompt}
                onChange={(e) => updatePersona(persona.id, { systemPrompt: e.target.value })}
                rows={3}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-xs font-mono text-zinc-300 focus:border-purple-500 focus:outline-none resize-none"
              />
            </div>

            {/* Modelfile & Ollama Publishing Controls */}
            <div className="flex flex-col gap-2 mt-1">
              <div className="flex gap-2.5">
                <button
                  type="button"
                  onClick={() => downloadModelfile(persona)}
                  className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-zinc-850 hover:bg-zinc-800 text-xs font-semibold rounded-lg text-zinc-300 transition-colors border border-zinc-800"
                  title="Download local Modelfile"
                >
                  <Download size={13} />
                  Export Modelfile
                </button>
                
                <button
                  type="button"
                  onClick={() => publishToOllama(persona)}
                  disabled={state.connectionType !== "ollama" || publishingStatus[persona.id] === "publishing"}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs font-semibold rounded-lg transition-colors border",
                    state.connectionType === "ollama"
                      ? "bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border-cyan-500/20 disabled:opacity-50"
                      : "bg-zinc-900/50 text-zinc-650 border-zinc-900 cursor-not-allowed"
                  )}
                  title={state.connectionType === "ollama" ? "Publish model directly to local Ollama" : "Ollama connection required to publish"}
                >
                  {publishingStatus[persona.id] === "publishing" ? (
                    <>
                      <div className="h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" />
                      Creating...
                    </>
                  ) : publishingStatus[persona.id] === "success" ? (
                    <>
                      <Check size={13} className="text-emerald-400" />
                      Created!
                    </>
                  ) : (
                    <>
                      <UploadCloud size={13} />
                      Publish to Ollama
                    </>
                  )}
                </button>
              </div>

              {/* Publish Error Message */}
              {publishingStatus[persona.id] === "error" && (
                <div className="flex items-start gap-1.5 text-[10px] text-red-400 mt-1 bg-red-950/20 p-2 rounded-lg border border-red-900/30">
                  <AlertCircle size={12} className="shrink-0 mt-0.5" />
                  <span>{publishingError[persona.id] || "Failed to publish."}</span>
                </div>
              )}
            </div>

          </div>
        ))}
        {state.activePersonas.length === 0 && (
          <div className="text-center p-8 border border-dashed border-zinc-800 rounded-2xl text-zinc-600 text-xs">
            No personas configured. Click "Add Persona" or reconnect to a server to auto-generate models.
          </div>
        )}
      </div>
    </div>
  );
}


